{
	"AGENT_MANUALLY_SHUT_DOWN": "Temsilci manuel olarak kapatÄ±ldÄ±.",
	"AGENT_MAXED_OUT_LOOPS": "Bu ajan dÃ¶ngÃ¼lerde maksimuma ulaÅŸtÄ±. \nCÃ¼zdanÄ±nÄ±zÄ± kurtarmak iÃ§in bu aracÄ± kapatÄ±lÄ±yor. \nGeliÅŸmiÅŸ ayarlarda dÃ¶ngÃ¼ sayÄ±sÄ±nÄ± yapÄ±landÄ±rabilirsiniz.",
	"ALL_TASKS_COMPLETETD": "TÃ¼m gÃ¶revler tamamlandÄ±. \nKapatmak.",
	"DEMO_LOOPS_REACHED": "ÃœzgÃ¼nÃ¼z, Ã§Ã¼nkÃ¼ bu bir demo, ajanlarÄ±mÄ±zÄ± Ã§ok uzun sÃ¼re Ã§alÄ±ÅŸtÄ±ramayÄ±z. \nDaha uzun Ã§alÄ±ÅŸtÄ±rmalar istiyorsanÄ±z, lÃ¼tfen Ayarlar'da kendi API anahtarÄ±nÄ±zÄ± saÄŸlayÄ±n. \nKapatmak.",
	"ERROR_ACCESSING_OPENAI_API_KEY": "OpenAI'nin API'sine eriÅŸirken HATA. \nLÃ¼tfen API anahtarÄ±nÄ±zÄ± kontrol edin veya daha sonra tekrar deneyin",
	"ERROR_ADDING_ADDITIONAL_TASKS": "Ek gÃ¶rev(ler) eklenirken HATA. \nBunlarÄ± Ã§alÄ±ÅŸtÄ±rmak modelimizin ilkelerine aykÄ±rÄ± olabilir. \nDevam ediyor.",
	"ERROR_API_KEY_QUOTA": "OpenAI API anahtarÄ±nÄ±zÄ± kullanÄ±rken HATA. \nMevcut kotanÄ±zÄ± aÅŸtÄ±nÄ±z, lÃ¼tfen planÄ±nÄ±zÄ± ve fatura ayrÄ±ntÄ±larÄ±nÄ±zÄ± kontrol edin.",
	"ERROR_OPENAI_API_KEY_NO_GPT4": "HATA, API anahtarÄ±nÄ±zÄ±n GPT-4 eriÅŸimi yok. \nÃ–nce OpenAI'nin bekleme listesine katÄ±lmalÄ±sÄ±nÄ±z. \n(Bu, ChatGPT Plus'tan farklÄ±dÄ±r)",
	"ERROR_RETRIEVE_INITIAL_TASKS": "Ä°lk gÃ¶revler dizisi alÄ±nÄ±rken HATA. \nYeniden deneyin, hedefinizi daha net hale getirin veya hedefinizi, Ã§alÄ±ÅŸtÄ±rÄ±lacak modelimizin politikalarÄ± dahilinde olacak ÅŸekilde revize edin. \nKapatmak.",
	"INVALID_OPENAI_API_KEY": "HATA geÃ§ersiz OpenAI API anahtarÄ±",
	"RATE_LIMIT_EXCEEDED": "HÄ±z limiti aÅŸÄ±ldÄ±! \nLÃ¼tfen yavaÅŸlayÄ±n...ğŸ˜…"
}
