{
    "ERROR_ACCESSING_OPENAI_API_KEY": "ERRORE durante l'accesso alla chiave API di OpenAI. Controllare la chiave API o riprovare pi√π tardi.",
    "ERROR_ADDING_ADDITIONAL_TASKS": "ERRORE durante l'aggiunta di ulteriori compiti. Potrebbe essere che il nostro modello non riesca a gestire la risposta e ci√≤ abbia generato l'errore. Continua...",
    "RATE_LIMIT_EXCEEDED": "Limite massimo di query raggiunto! Si prega di rallentare...üòÖ",
    "AGENT_MAXED_OUT_LOOPS": "Questo agente ha raggiunto il numero massimo di cicli eseguibili. Per salvare il portafoglio, questo agente si fermer√† ora... Il numero massimo di cicli di esecuzione dell'agente pu√≤ essere configurato nelle impostazioni.",
    "DEMO_LOOPS_REACHED": "Spiacente, poich√© questa √® un'applicazione demo, non possiamo far funzionare gli agenti per troppo tempo. Nota: se desideri eseguire cicli pi√π lunghi, fornisci una chiave API personalizzata nelle Impostazioni. Si ferma...",
    "AGENT_MANUALLY_SHUT_DOWN": "Agente arrestato manualmente.",
    "ALL_TASKS_COMPLETETD": "Tutti i compiti sono stati completati. Arresto...",
    "ERROR_API_KEY_QUOTA": "ERRORE nell'uso della chiave API di OpenAI. Hai superato la tua quota corrente, controlla le tue informazioni di fatturazione.",
    "ERROR_OPENAI_API_KEY_NO_GPT4": "ERRORE: la tua chiave API di OpenAI non ha accesso a GPT-4. Prima devi registrarti nella lista d'attesa di OpenAI. (Ci√≤ differisce da ChatGPT Plus)",
    "ERROR_RETRIEVE_INITIAL_TASKS": "ERRORE durante il recupero dei compiti iniziali. Riprova, formulando pi√π chiaramente l'obiettivo dell'agente o modificandolo in modo che sia conforme al nostro modello. Arresto...",
    "INVALID_OPENAI_API_KEY": "ERRORE chiave API OpenAI non valida"
}